services:
  - type: web
    name: gemsearch
    runtime: python
    buildCommand: "pip install torch==2.2.2 torchvision==0.17.2 --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: QDRANT_URL
        value: https://e6fff43d-09ee-4f26-bf4d-cef8af87f057.us-west-1-0.aws.cloud.qdrant.io
      - key: QDRANT_API_KEY
        sync: false
      - key: CLIP_MODEL
        value: ViT-B-32
      - key: CLIP_PRETRAINED
        value: openai
      - key: REMBG_PREPROCESSING
        value: "false"
